version: "3.8"

services:
  db:
    image: postgres:12.2-alpine 
    container_name: "comments-databse"
    ports:
      - "5432:5432"
    environment: #environment variables when database start up
      - POSTGRES_DB=postgres
      - POSTREES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes: 
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "comments-rest-api"
    environment: 
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"        
      DB_DB: "postgres"
      DB_HOST: "db"    # should match db as db service
      DB_TABLE: "postgres"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:  
      - fullstack 
volumes:
  database_postgres:  # match database_postgres:/var/lib/postgresql/data
    
networks:
  fullstack:
      driver: bridge        

